# Generated by Django 2.2 on 2019-04-15 16:50

import animesuki.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('media_type', models.PositiveSmallIntegerField(choices=[(1, 'Anime'), (2, 'Manga'), (3, 'Novel')], default=1, verbose_name='type')),
                ('sub_type', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), ('Anime', ((1, 'TV'), (2, 'OVA'), (3, 'Movie'), (4, 'Web'), (5, 'Special'), (6, 'Music'))), ('Manga', ((7, 'Manga'), (8, 'Manhua'), (9, 'Manhwa'), (10, 'Web Manga'), (11, 'One Shot'), (12, 'Doujin'))), ('Novel', ((13, 'Light Novel'), (14, 'Web Novel'), (15, 'Novel')))], default=0, verbose_name='sub Type')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Automatic'), (2, 'On Hiatus'), (3, 'Cancelled')], default=1, verbose_name='status')),
                ('is_adult', models.BooleanField(default=False, verbose_name='r-18')),
                ('episodes', models.IntegerField(blank=True, null=True, verbose_name='episodes')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='duration')),
                ('volumes', models.IntegerField(blank=True, null=True, verbose_name='volumes')),
                ('chapters', models.IntegerField(blank=True, null=True, verbose_name='chapters')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('start_precision', models.PositiveSmallIntegerField(choices=[(1, 'Full'), (2, 'Year'), (3, 'Month')], default=1, verbose_name='precision')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('end_precision', models.PositiveSmallIntegerField(choices=[(1, 'Full'), (2, 'Year'), (3, 'Month')], default=1, verbose_name='precision')),
                ('season_year', models.IntegerField(blank=True, null=True, verbose_name='season year')),
                ('season', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Winter'), (2, 'Spring'), (3, 'Summer'), (4, 'Fall')], null=True, verbose_name='season')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('synopsis', models.TextField(blank=True, verbose_name='synopsis')),
            ],
            options={
                'verbose_name_plural': 'media',
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='MediaArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=animesuki.core.models.artwork_upload_location)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.Media')),
            ],
            options={
                'db_table': 'media_artwork',
            },
        ),
        migrations.AddField(
            model_name='media',
            name='artwork',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_artwork', to='media.MediaArtwork'),
        ),
    ]
